language: csharp
solution: WebApplication1/WebApplication1.sln
env:
  global:
  - secure: KyUk1PZyhyAV56MQVbOh3zhd9MQvBUvX26ZtHOqXbRTtnpSv+jv5XEcS+SETl3/SWpwXi7jyPxgz53vvXdoIxV4R7VgMUg3wiZZF4ygTXWF7m2Q5tD7NqQONmOS0Y3o+RCXCD0yb+eGJFn5tuGHIsfPWfxkt5S/w4lrXAeKD0Js=
  - secure: YX+f6oU7B6kIUaIunje1yOt+XTIYW/gdg+x8L4w6aZCX+5rHco7XtYkPikDREtzMJdhLWijAajjTa3FOCAZIm3j2UKBP1ecxiCxludCKVtPnbkL8NYEIMa52y6xaUPNb8YA4Uzci6hZC2Ky1qldNijLtB1VYEkbSxNOH6CpA1rw=
before_install:
- sudo apt-get install -qq lftp
after_success:
- pwd
- ls
- 'lftp -p 21 -e "set ftp:ssl-allow no; mirror -R . /" -u $FTPUSER,$FTPPASSWORD 72.18.134.185'
#- "curl --ftp-create-dirs -T WebApplication1/WebApplication1.sln -u $FTPUSER:$FTPPASSWORD ftp://72.18.134.185:21/"

